name: express setup
on: 
  workflow_dispatch:
   inputs:
    workload_identity_provider:
      required: true
    service_account:
      required: true
    audience:
      required: true
      
jobs:
  stack-initialization:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        
        - name: generate scaffold
          run: |
            npx express-generator temp-scaffold
            cp -r temp-scaffold/* .
            rm -rf temp-scaffold

        - name: Commit files
          run: |
            git config --global user.name '${{github.actor}}'
            git config --global user.email '${{github.actor}}@users.noreply.github.com'
            git add -A
            git commit -m "Added scaffold."
            git push
       
  deploy-to-aws:
    needs: stack-initialization
    uses: raju-dasupally/node-azure-stack/.github/workflows/express_gcp_deploy.yml@main
    with:
      index: ${{needs.build.outputs.artifact_name}}
      workload_identity_provider: ${{github.event.inputs.workload_identity_provider}}
      service_account: ${{github.event.inputs.service_account}}
      audience: ${{github.event.inputs.audience}}

  create-readme:
    needs: deploy-to-aws
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: git pull
    
      - name: move some folders around
        run: |
          mv ./instance-contents/README.md ./README.md
          rm -r ./instance-contents
          printf '%s\n%s\n' "## Find your app hosted at ${{ needs.deploy-to-aws.outputs.app_url }}" "$(cat README.md)" >README.md
          

      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added readme."
          git push
